global:
  #scrape_interval: 120s # Default scrape interval
  scrape_interval: 60s # Default scrape interval

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Prometheus itself

  - job_name: 'node-exporter'
    static_configs:
      # Use the internal docker network hostname 'node-exporter'
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      # Use the internal docker network hostname 'cadvisor' and its internal port 8080
      - targets: ['cadvisor:8080']

  - job_name: 'minio'
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
      - targets: ['server1:9000']

  - job_name: 'stalwart-mail'
    metrics_path: /metrics/prometheus
    scheme: http
    static_configs:
      - targets: ['stalwart:8080']

  - job_name: 'ybdb'
    metrics_path: /prometheus-metrics # Standard MinIO metrics path
    scheme: http # Assuming no TLS within the docker network
    static_configs:
      - targets: ['server1:7000']
